CREATE SCHEMA IF NOT EXISTS rsbdev;
CREATE SCHEMA IF NOT EXISTS softplan;
CREATE SCHEMA IF NOT EXISTS agriness;

SET SCHEMA rsbdev;

CREATE TABLE USUARIO(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    TENANT VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    ROLETYPE VARCHAR(255) NOT NULL,
    LASTPASSWORDRESETDATE TIMESTAMP NOT NULL,
);

INSERT INTO USUARIO (ID, NAME, TENANT, PASSWORD, EMAIL, ROLETYPE, LASTPASSWORDRESETDATE) VALUES 
(1, 'admin', 'rsbdev', '$2a$10$jextB2Q6lPOQW6Dpl2uwLuT.pQsuZkkQMQBtj6BlmB899mDh6lw9.',  'admin@admin.com', 'ROLE_ADMIN', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy')),
(2, 'softplan', 'softplan', '$2a$10$jextB2Q6lPOQW6Dpl2uwLuT.pQsuZkkQMQBtj6BlmB899mDh6lw9.',  'softplan@admin.com', 'ROLE_ADMIN', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy')),
(3, 'agriness', 'agriness', '$2a$10$jextB2Q6lPOQW6Dpl2uwLuT.pQsuZkkQMQBtj6BlmB899mDh6lw9.',  'agriness@admin.com', 'ROLE_ADMIN', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

CREATE TABLE PESSOA(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

INSERT INTO PESSOA (ID, NAME) VALUES 
(1, 'Renato'),
(2, 'Fabio'),
(3, 'Hugo');

SET SCHEMA softplan;

CREATE TABLE PESSOA(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

INSERT INTO PESSOA (ID, NAME) VALUES 
(1, 'Zunino'),
(2, 'Florão'),
(3, 'Justi');

SET SCHEMA agriness;

CREATE TABLE PESSOA(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

INSERT INTO PESSOA (ID, NAME) VALUES
(1, 'Marcos'),
(2, 'Rangel'),
(3, 'Gustavo Mind Set');